import asyncio
import logging
from typing import Any, AsyncIterator

from sdk.agent_sdk import AgentRole, AgentState
from .base_agent import BaseAgent

logger = logging.getLogger(__name__)


class CoderAgent(BaseAgent):
    name = "coder"
    role = AgentRole.CODER
    description = "Writes, reviews, and debugs code"

    async def get_system_prompt(self) -> str:
        return """You are the Coder Agent. Your role is to:
1. Write clean, production-quality code
2. Follow best practices and design patterns
3. Include proper error handling
4. Write type hints and documentation
5. Optimize for performance and readability
6. Generate tests alongside implementation
7. Review and refactor existing code
8. Debug and fix issues

Always output complete, working code solutions."""

    async def run(self, task: str, **kwargs: Any) -> AsyncIterator[str]:
        await self.update_state(AgentState.THINKING)
        yield f"💻 **Coder** implementing...\n\n"

        await asyncio.sleep(0.3)
        language = kwargs.get("language", "python")
        yield f"**Task:** {task}\n"
        yield f"**Language:** {language}\n\n"

        await self.update_state(AgentState.EXECUTING)
        yield f"```{language}\n"
        yield f"# Generated by MKCode Coder Agent\n"
        yield f"# Task: {task}\n\n"

        if language == "python":
            yield f"import logging\nfrom typing import Any, Optional\n\nlogger = logging.getLogger(__name__)\n\n\nclass Solution:\n    \"\"\"Solution implementation for: {task}\"\"\"\n\n    def __init__(self):\n        self.logger = logger\n\n    async def execute(self, **kwargs: Any) -> dict[str, Any]:\n        try:\n            result = await self._process(**kwargs)\n            return {{\"success\": True, \"data\": result}}\n        except Exception as e:\n            self.logger.error(f\"Execution failed: {{e}}\")\n            return {{\"success\": False, \"error\": str(e)}}\n\n    async def _process(self, **kwargs: Any) -> Any:\n        return {{\"status\": \"implemented\", \"task\": \"{task}\"}}\n"
        elif language in ("javascript", "typescript"):
            yield f"/**\n * Solution for: {task}\n */\n\nexport async function execute(params: Record<string, any> = {{}}): Promise<any> {{\n  try {{\n    console.log(\"Executing:\", params);\n    return {{ success: true, data: {{ status: \"implemented\" }} }};\n  }} catch (error) {{\n    console.error(\"Execution failed:\", error);\n    return {{ success: false, error: String(error) }};\n  }}\n}}\n"

        yield f"```\n\n"
        await asyncio.sleep(0.3)
        yield f"✅ Code generated successfully.\n"
        await self.update_state(AgentState.COMPLETED)

    async def update_state(self, state: AgentState) -> None:
        if self._agent:
            self._agent.state = state
